In [1]:
%pylab inline
%config InlineBackend.figure_format = 'retina'
from ipywidgets import interact

Populating the interactive namespace from numpy and matplotlib


In [2]:
def backward_substitution(U, b):
    """Upper triangular matrix `U` and right hand side vector `b`. 
    Note that `U` must be square and `U` & `b` must have compatable shape."""
    b = array(b)
    assert b.size > 1
    assert b.ndim == 1 or b.ndim == 2
    n = b.size
    assert all(diag(U) != 0), 'the diagonal elements of U must be nonzero'
    assert U.ndim == 2
    assert all(array(U.shape) == n), 'the matrix U must be square and must have same number of rows as b'
    n = b.size
    x = ones_like(b)
    for k in arange(n)[::-1]: ## iterate in reverse order
        q = 0.
        for j in arange(k+1, n):
            q = q + U[k, j]*x[j]
        x[k] = (b[k] - q)/U[k, k]
    return x
def forward_substitution(L, b):
    """Lower triangular matrix `L` and right hand side vector `b`. 
    Note that `L` must be square and `L` & `b` must have compatable shape."""
    b = array(b)
    assert b.size > 1
    assert b.ndim == 1 or b.ndim == 2
    n = b.size
    assert all(diag(L) != 0), 'the diagonal elements of L must be nonzero'
    assert L.ndim == 2
    assert all(array(L.shape) == n), 'the matrix L must be square and must have same number of rows as b'
    x = ones_like(b)
    for k in arange(n):
        q = 0.
        for j in arange(k):
            q = q + L[k, j]*x[j]
        x[k] = (b[k] - q)/L[k, k]
    return x

# A test problem

In [3]:
m = 10
n = 5
A = -10 + 20*rand(m, n)
b = ones((m, 1))
print('A=')
print(around(A, 3))
print('b=')
print(around(b, 3))

A=
[[-8.561 -3.29  -1.752  5.312  7.127]
 [-5.902 -8.898 -1.706  7.366 -0.768]
 [-5.717 -0.32  -5.276  1.877 -2.258]
 [ 7.993 -4.316  8.35   6.733  1.67 ]
 [ 7.258 -2.577 -2.816 -0.251  7.706]
 [ 8.241 -7.261 -6.154 -5.986 -4.072]
 [-3.134  5.429 -0.824 -4.313  5.669]
 [ 8.817 -7.468 -5.868 -8.483  5.321]
 [-7.916  1.883  8.959  1.944  8.58 ]
 [ 2.695  8.191  9.483 -2.654 -1.9  ]]
b=
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]]


# LU (Cholesky) Decomposition

In [4]:
M = A.T@A
L = cholesky(M) ## This returns a lower triangular matrix such that M = L@L.T
y = forward_substitution(L, A.T@b)
x = backward_substitution(L.T, y)
print('residual', norm(A@x - b))

residual 1.8128686496108235


# QR Decomposition

In [5]:
## If you want the full QR decomposition, use `mode='full'`
Qhat, Rhat = qr(A, mode='reduced') 
y = Qhat.T@b
x = backward_substitution(Rhat, y)
print('residual', norm(A@x - b))

residual 1.8128686496108233


# Singular Value Decomposition

In [7]:
## If you want the full SVD decomposition, use `full_matrices=True`
Uhat, sigma, Vhat_T = svd(A, full_matrices=False) ## sigma is the vector of diagonal entries, not the matrix
Vhat = Vhat_T.T
assert b.shape == (m, 1), 'make sure b is m x 1'
y = (1/sigma[:, None])*(Uhat.T@b) ## this is equivalent to solving Sigma_hat@y = Uhat.T@b
x = Vhat@y
print('residual', norm(A@x - b))

residual 2.4526302696176145
